### ISSUE TITLE
Adding a user friendly Identifier to a device

### ISSUE THREAD

**Issue by syryna** [iobroker-community-adapters/ioBroker.enocean#26]
Hi,

I would like to request a change so a user can give a device a proper user friendly Identifier. I have many actors and switches and the cryptic IDs will confuse.

It also might be later usefull for VIS to output a self-explaining name instead of the internal ID.

Here is a mockup as an example:
[https://snag.gy/AnTWrN.jpg](url)

I can do the change myself and send you a pull-request if you allow me to do it.

Regards, Michael

**Comment by Jey-Cee** [comment]
You know the row 'Name' in Object tab? This is where you can change it. 
But if you want to make it possible to do this inside the config, it is ok. If you do so make sure it will change the name attribute and not the ID.

Btw: I am not a friend of naming like this, it is better to use enums. Also it is better for scripting.

**Comment by Jey-Cee** [comment]
You can do that already, go to object tab and change the name.
